# Generated by Django 5.0.2 on 2024-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, verbose_name='Product name')),
                ('photo', models.CharField(max_length=255, verbose_name='Rasm link')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category_code', models.CharField(max_length=20, verbose_name='Category code')),
                ('category_name', models.CharField(max_length=30, verbose_name='Categoryname')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Subcategory code')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Subcategory name')),
            ],
        ),
    ]
