# Generated by Django 5.0.2 on 2024-02-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Telegram username')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Phone number')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat id')),
            ],
        ),
    ]
